# Generated by Django 4.1.10 on 2023-08-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
